name: project-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
    - mlflow
    - jupyter
    - scikit-learn
    - pandas
    - seaborn
    - hyperopt
    - xgboost
    - fastparquet
    - boto3
